export const ScenariosList = [
    {
        "id": "3514a036-f1fc-473a-adee-c9801547ca8e",
        "agentId": "79adf522-650a-4db2-a9d3-987f42cf802d",
        "name": "High complexity test",
        "description": "High complexity testing",
        "userMessage": "High complexity test",
        "expectedTools": [
            {
                "name": "High complexity",
                "parameters": {
                    "date": "2026-02-27"
                }
            }
        ],
        "complexity": "high",
        "targetCategory": "other",
        "isAutoGenerated": true,
        "createdAt": "2026-01-27T06:08:42.134Z"
    },
    {
        "id": "e6d9881b-ceec-4551-a441-9cc253e88c3d",
        "agentId": "79adf522-650a-4db2-a9d3-987f42cf802d",
        "name": "Edge Case High complexity - paginate 8",
        "description": "Edge Case testing",
        "userMessage": "Edge Case test",
        "expectedTools": [
            {
                "name": "Edge Case High High complexity",
                "parameters": {
                    "date": "2026-03-27"
                }
            }
        ],
        "complexity": "high",
        "targetCategory": "edge_case",
        "isAutoGenerated": true,
        "createdAt": "2026-01-27T04:54:29.411Z"
    },
    {
        "id": "23ca346e-7ace-4727-8935-888108506907",
        "agentId": "79adf522-650a-4db2-a9d3-987f42cf802d",
        "name": "Edge Case High complexity - paginate 7",
        "description": "Edge Case testing",
        "userMessage": "Edge Case test",
        "expectedTools": [
            {
                "name": "Edge Case High High complexity",
                "parameters": {
                    "date": "2026-03-27"
                }
            }
        ],
        "complexity": "high",
        "targetCategory": "edge_case",
        "isAutoGenerated": true,
        "createdAt": "2026-01-27T04:54:21.560Z"
    },
    {
        "id": "690ececf-c63f-4e3b-b62a-17a9ec5d69ea",
        "agentId": "79adf522-650a-4db2-a9d3-987f42cf802d",
        "name": "Edge Case High complexity - paginate 6",
        "description": "Edge Case testing",
        "userMessage": "Edge Case test",
        "expectedTools": [
            {
                "name": "Edge Case High High complexity",
                "parameters": {
                    "date": "2026-03-27"
                }
            }
        ],
        "complexity": "high",
        "targetCategory": "edge_case",
        "isAutoGenerated": true,
        "createdAt": "2026-01-27T04:54:14.322Z"
    },
    {
        "id": "3dfd555a-cc48-46e4-8901-9f5e355e5e40",
        "agentId": "79adf522-650a-4db2-a9d3-987f42cf802d",
        "name": "Edge Case High complexity - paginate 5",
        "description": "Edge Case testing",
        "userMessage": "Edge Case test",
        "expectedTools": [
            {
                "name": "Edge Case High High complexity",
                "parameters": {
                    "date": "2026-03-27"
                }
            }
        ],
        "complexity": "high",
        "targetCategory": "edge_case",
        "isAutoGenerated": true,
        "createdAt": "2026-01-27T04:54:06.172Z"
    }
]