import React, { useState } from 'react'
import { AgentsList1 } from '../../assets/data/TestAgentsData'

function CreateScenario({ onCancel }) {

  const [form, setForm] = useState({
    agentId: AgentsList1[0]?.id || '',
    name: '',
    description: '',
    userMessage: '',
    expectedTools: '[]',
    complexity: 'simple',
    targetCategory: 'happy_path'
  })

  const [error, setError] = useState(null)
  const [loading, setLoading] = useState(false)

  function handleFormChange(e) {
    const { name, value } = e.target
    setForm(prev => ({ ...prev, [name]: value }))
  }

  function validate() {
    if (!form.agentId) return 'Agent is required'
    if (!form.name.trim()) return 'Scenario name is required'
    if (!form.userMessage.trim()) return 'User message is required'

    try {
      JSON.parse(form.expectedTools)
    } catch {
      return 'Expected tools must be valid JSON'
    }

    return null
  }

  async function handleSubmit(e) {
    e.preventDefault()
    setError(null)

    const validationError = validate()
    if (validationError) {
      setError(validationError)
      return
    }

    setLoading(true)

    try {
      const scenarioData = {
        name: form.name,
        description: form.description,
        userMessage: form.userMessage,
        expectedTools: JSON.parse(form.expectedTools),
        complexity: form.complexity,
        targetCategory: form.targetCategory,
        isAutoGenerated: false
      }

      const res = await fetch(`${import.meta.env.VITE_API_URL}/api/agents/${form.agentId}/scenarios`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(scenarioData)
      })

      if (!res.ok) {
        throw new Error(`HTTP error: ${res.status}`)
      }

      // const data = await res.json()
      if (res.status === 201) {
        alert('Scenario created successfully')
        onCancel()
      }


    } catch (error) {
      console.error(error)
      setError('Failed to create scenario')
    } finally {
      setLoading(false)
    }
  }


  return (
    <div className="max-w-3xl mx-auto py-6 px-4 md:px-8 bg-white rounded-lg pb-24">
      <h2 className="text-xl font-semibold mb-4">Create Test Scenario</h2>

      {error && (
        <div className="mb-4 p-3 rounded bg-red-50 text-red-600">
          {error}
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-4">

        {/* Agent */}
        <div>
          <label className="block text-sm font-medium mb-1">
            Assign Agent *
          </label>
          <select
            name="agentId"
            value={form.agentId}
            onChange={handleFormChange}
            className="w-full border rounded px-3 py-2"
          >
            {AgentsList1.map(agent => (
              <option key={agent.id} value={agent.id}>
                {agent.name}
              </option>
            ))}
          </select>
        </div>

        {/* Scenario Name */}
        <div>
          <label className="block text-sm font-medium mb-1">
            Scenario Name *
          </label>
          <input
            name="name"
            value={form.name}
            onChange={handleFormChange}
            className="w-full border rounded px-3 py-2"
            placeholder="e.g. Customer Refund Request Handling"
          />
        </div>

        {/* Description */}
        <div>
          <label className="block text-sm font-medium mb-1">
            Description *
          </label>
          <textarea
            name="description"
            value={form.description}
            onChange={handleFormChange}
            className="w-full border rounded px-3 py-2"
            rows={3}
          />
        </div>

        {/* User Message */}
        <div>
          <label className="block text-sm font-medium mb-1">
            User Message *
          </label>
          <textarea
            name="userMessage"
            value={form.userMessage}
            onChange={handleFormChange}
            className="w-full border rounded px-3 py-2"
            rows={3}
          />
        </div>

        {/* Expected Tools */}
        <div>
          <label className="block text-sm font-medium mb-1">
            Expected Tools (JSON)
          </label>
          <textarea
            name="expectedTools"
            value={form.expectedTools}
            onChange={handleFormChange}
            className="w-full border rounded px-3 py-2 font-mono text-sm"
            rows={4}
          />
        </div>

        {/* Complexity */}
        <div>
          <label className="block text-sm font-medium mb-1">
            Complexity *
          </label>
          <select
            name="complexity"
            value={form.complexity}
            onChange={handleFormChange}
            className="w-full border rounded px-3 py-2"
          >
            <option value="simple">Simple</option>
            <option value="moderate">Moderate</option>
            <option value="high">High</option>
          </select>
        </div>

        {/* Target Category */}
        <div>
          <label className="block text-sm font-medium mb-1">
            Target Category *
          </label>
          <select
            name="targetCategory"
            value={form.targetCategory}
            onChange={handleFormChange}
            className="w-full border rounded px-3 py-2"
          >
            <option value="happy_path">Happy Path</option>
            <option value="edge_case">Edge Case</option>
            <option value="adversarial">Adversarial</option>
            <option value="other">Other</option>
          </select>
        </div>

        {/* Actions */}
        <div className="flex gap-3 pt-4">
          <button
            type="button"
            onClick={onCancel}
            className="px-4 py-2 rounded bg-gray-100 cursor-pointer"
          >
            Cancel
          </button>

          <button
            type="submit"
            disabled={loading}
            className="px-4 py-2 rounded bg-blue-700 text-white disabled:opacity-50 cursor-pointer"
          >
            {loading ? 'Creating...' : 'Create Scenario'}
          </button>
        </div>
      </form>
    </div>
  )
}

export default CreateScenario