import express from "express"
import { prisma} from '../db/prisma.js'

const router = express.Router()

router.post('/agents/:agentId/scenarios', async (req, res) => {
    const {
        name,
        description,
        userMessage,
        expectedTools,
        complexity,
        targetCategory,
        isAutoGenerated
    } = req.body

    const { agentId } = req.params

    try {
        // Check agent exists
        const agentExist = await prisma.agent.findUnique({
            where: {
                id: agentId
            }
        })

        if (!agentExist) {
            return res.status(404).send({
                error: {
                    message: "Agent not found"
                }
            })
        }

        if (!name || name.length < 3 || name.length > 100) {
            return res.status(400).json({ message: 'Name must be 3–100 characters' })
        }

        if (!userMessage || userMessage.length < 10 || userMessage.length > 500) {
            return res.status(400).json({ message: 'User message must be 10–500 characters' })
        }

        const scenario = await prisma.scenario.create({
            data: {
                name,
                description,
                userMessage,
                expectedTools,
                complexity,
                targetCategory,
                isAutoGenerated,
                agent: {
                    connect: {
                        id: agentId
                    }
                }
            }
        })
        return res.status(201).json(scenario)

    } catch (error) {
        console.error(error)
        return res.status(500).json({ message: 'Internal server error' })
    }
})

router.get('/scenario/:id', async (req, res) => {
    const { id } = req.params

    try {
        const scenario = await prisma.scenario.findUnique({
            where: {
                id
            }
        })

        if (!scenario) {
            return res.status(404).json({ message: 'Scenario not found' })
        }

        return res.status(200).json(scenario)
    } catch (error) {
        console.error(error)
        return res.status(500).json({ message: 'Internal server error' })
    }
})


router.get('/agents/:agentId/scenarios', async (req, res) => {
    const { agentId } = req.params
    const page = parseInt(req.query.page) || 1
    const limit = parseInt(req.query.limit) || 20
    const skip = (page - 1) * limit

    try {
        const agentExist = await prisma.agent.findUnique({
            where: {
                id: agentId
            }
        })

        if (!agentExist) {
            return res.status(404).json({ message: 'Agent not found' })
        }

        const scenarios = await prisma.scenario.findMany({
            where: {
                agentId
            },
            orderBy: { createdAt: 'desc' },
            skip,
            take: limit
        })

        const pageDetails = await prisma.scenario.count({
            where: {
                agentId
            }
        })

        const pagination = {
            page, pageDetails, totalPages: Math.ceil(pageDetails / limit)
        }

        return res.status(200).json({
            pagination, scenarios
        })

    } catch (error) {
        console.error(error)
        return res.status(500).json({ message: 'Internal server error' })
    }


})

router.delete('/scenario/:id', async (req, res) => {
    const { id } = req.params

    try {
        await prisma.scenario.delete({
            where: {
                id
            }
        })

        return res.status(200).json({ message: 'Scenario deleted successfully' })
    } catch (error) {
        console.error(error)

        if (error.code === 'P2025') {
            return res.status(404).json({ message: 'Scenario not found' })
        }

        return res.status(500).json({ message: 'Internal server error' })
    }
})





export default router