import express from "express"
import { prisma} from '../db/prisma.js'

const router = express.Router()

router.post('/agents/:agentId/scenarios', async (req, res) => {
    const {
        name,
        description,
        userMessage,
        expectedTools,
        complexity,
        targetCategory,
        isAutoGenerated
    } = req.body

    const { agentId } = req.params

    try {
        // Check agent exists
        const agentExist = await prisma.agent.findUnique({
            where: {
                id: agentId
            }
        })

        if (!agentExist) {
            return res.status(404).send({
                error: {
                    message: "Agent not found"
                }
            })
        }

        if (!name || name.length < 3 || name.length > 100) {
            return res.status(400).json({ message: 'Name must be 3–100 characters' })
        }

        if (!userMessage || userMessage.length < 10 || userMessage.length > 500) {
            return res.status(400).json({ message: 'User message must be 10–500 characters' })
        }

        const scenario = await prisma.scenario.create({
            data: {
                name,
                description,
                userMessage,
                expectedTools,
                complexity,
                targetCategory,
                isAutoGenerated,
                agent: {
                    connect: {
                        id: agentId
                    }
                }
            }
        })
        return res.status(201).json(scenario)

    } catch (error) {
        console.error(error)
        return res.status(500).json({ message: 'Internal server error' })
    }
})





export default router